language: python

python:
  - "2.7"

before_install:
    - pip install pep8

install:
    - python setup.py -q install

script:
    - echo "this is a test"
    - find . -name \*.py -exec pep8 {} +
    - ./run_tests.sh
