language: python

python:
  - "2.7"

before_install:
    - pip install pep8

install:
    - python setup.py -q install

script:
    - find . -name \*.py -exec pep8 --ignore=E501,E226 --exclude='*/procedural_city_generation/*' {} +
    - ./run_tests.sh
